name: pulse
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^16.3.0
  stylish_bottom_bar: ^1.1.0
  material_symbols_icons: ^4.2810.1
  network_info_plus: ^7.0.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  share_plus: ^12.0.1
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.2.0
  http: ^1.3.0
  path_provider: ^2.1.5
  dart_ping: ^9.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  syncfusion_flutter_charts: ^31.2.5
  url_launcher: ^6.3.1
  open_settings_plus: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env

msix_config:
  display_name: Pulse
  publisher_display_name: Pranta Dutta
  identity_name: com.pranta.pulse
  msix_version: 1.0.0.0
  languages: en-us
  capabilities: "internetClient,location"
  logo_path: assets/pulse_500x500_logo.png
